# Ensemble Learning

## Initial Imports

In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import numpy as np
import pandas as pd
from pathlib import Path
from collections import Counter

In [3]:
from sklearn.metrics import balanced_accuracy_score
from imblearn.metrics import geometric_mean_score
from sklearn.metrics import confusion_matrix
from imblearn.metrics import classification_report_imbalanced

## Read the CSV and Perform Basic Data Cleaning

In [4]:
# Load the data
file_path = Path('Resources/LoanStats_2019Q1.csv')
df = pd.read_csv(file_path)

# Preview the data
df.head()

,loan_amnt,int_rate,installment,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,dti,...,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,debt_settlement_flag
0,10500.0,0.1719,375.35,RENT,66000.0,Source Verified,Mar-2019,low_risk,n,27.24,...,85.7,100.0,0.0,0.0,65687.0,38199.0,2000.0,61987.0,N,N
1,25000.0,0.2000,929.09,MORTGAGE,105000.0,Verified,Mar-2019,low_risk,n,20.23,...,91.2,50.0,1.0,0.0,271427.0,60641.0,41200.0,49197.0,N,N
2,20000.0,0.2000,529.88,MORTGAGE,56000.0,Verified,Mar-2019,low_risk,n,24.26,...,66.7,50.0,0.0,0.0,60644.0,45684.0,7500.0,43144.0,N,N
3,10000.0,0.1640,353.55,RENT,92000.0,Verified,Mar-2019,low_risk,n,31.44,...,100.0,50.0,1.0,0.0,99506.0,68784.0,19700.0,76506.0,N,N
4,22000.0,0.1474,520.39,MORTGAGE,52000.0,Not Verified,Mar-2019,low_risk,n,18.76,...,100.0,0.0,0.0,0.0,219750.0,25919.0,27600.0,20000.0,N,N

## Split the Data into Training and Testing

In [5]:
# Create our features
X = df.drop(columns='loan_status')

# Create our target
target = ["loan_status"]
y = df.loc[:, target].copy()

In [6]:
#getting the dataset to be binary encoded
X = pd.get_dummies(X)
X.head()

,loan_amnt,int_rate,installment,annual_inc,dti,delinq_2yrs,inq_last_6mths,open_acc,pub_rec,revol_bal,...,issue_d_Mar-2019,pymnt_plan_n,initial_list_status_f,initial_list_status_w,next_pymnt_d_Apr-2019,next_pymnt_d_May-2019,application_type_Individual,application_type_Joint App,hardship_flag_N,debt_settlement_flag_N
0,10500.0,0.1719,375.35,66000.0,27.24,0.0,0.0,8.0,0.0,1609.0,...,1,1,0,1,0,1,1,0,1,1
1,25000.0,0.2000,929.09,105000.0,20.23,0.0,0.0,17.0,1.0,18368.0,...,1,1,0,1,0,1,1,0,1,1
2,20000.0,0.2000,529.88,56000.0,24.26,0.0,0.0,8.0,0.0,13247.0,...,1,1,0,1,0,1,1,0,1,1
3,10000.0,0.1640,353.55,92000.0,31.44,0.0,1.0,10.0,1.0,17996.0,...,1,1,0,1,0,1,1,0,1,1
4,22000.0,0.1474,520.39,52000.0,18.76,0.0,1.0,14.0,0.0,9091.0,...,1,1,0,1,0,1,1,0,1,1

In [7]:
X.describe()

,loan_amnt,int_rate,installment,annual_inc,dti,delinq_2yrs,inq_last_6mths,open_acc,pub_rec,revol_bal,...,issue_d_Mar-2019,pymnt_plan_n,initial_list_status_f,initial_list_status_w,next_pymnt_d_Apr-2019,next_pymnt_d_May-2019,application_type_Individual,application_type_Joint App,hardship_flag_N,debt_settlement_flag_N
count,68817.000000,68817.000000,68817.000000,6.881700e+04,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,...,68817.000000,68817.0,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.0,68817.0
mean,16677.594562,0.127718,480.652863,8.821371e+04,21.778153,0.217766,0.497697,12.587340,0.126030,17604.142828,...,0.177238,1.0,0.123879,0.876121,0.383161,0.616839,0.860340,0.139660,1.0,1.0
std,10277.348590,0.048130,288.062432,1.155800e+05,20.199244,0.718367,0.758122,6.022869,0.336797,21835.880400,...,0.381873,0.0,0.329446,0.329446,0.486161,0.486161,0.346637,0.346637,0.0,0.0
min,1000.000000,0.060000,30.890000,4.000000e+01,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000,...,0.000000,1.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.0,1.0
25%,9000.000000,0.088100,265.730000,5.000000e+04,13.890000,0.000000,0.000000,8.000000,0.000000,6293.000000,...,0.000000,1.0,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000,1.0,1.0
50%,15000.000000,0.118000,404.560000,7.300000e+04,19.760000,0.000000,0.000000,11.000000,0.000000,12068.000000,...,0.000000,1.0,0.000000,1.000000,0.000000,1.000000,1.000000,0.000000,1.0,1.0
75%,24000.000000,0.155700,648.100000,1.040000e+05,26.660000,0.000000,1.000000,16.000000,0.000000,21735.000000,...,0.000000,1.0,0.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.0,1.0
max,40000.000000,0.308400,1676.230000,8.797500e+06,999.000000,18.000000,5.000000,72.000000,4.000000,587191.000000,...,1.000000,1.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.0,1.0

In [8]:
# Check the balance of our target values
y['loan_status'].value_counts()

low_risk     68470
high_risk      347
Name: loan_status, dtype: int64

In [9]:
# Split the X and y into X_train, X_test, y_train, y_test
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test= train_test_split(X, 
                                                   y, 
                                                   random_state=1)
X_train.shape

(51612, 95)

## Data Pre-Processing

Scale the training and testing data using the `StandardScaler` from `sklearn`. Remember that when scaling the data, you only scale the features data (`X_train` and `X_testing`).

In [10]:
# Create the StandardScaler instance
from sklearn.preprocessing import StandardScaler
data_scaler = StandardScaler()

In [11]:
# Fit the Standard Scaler with the training data
# When fitting scaling functions, only train on the training dataset
Scaler =data_scaler.fit(X_train)

In [12]:
# Scale the training and testing data
Xtrained_data_scaled = data_scaler.transform(X_train)
Xtrained_data_scaled[5]
Xtest_data_scaled = data_scaler.transform(X_test)
Xtest_data_scaled[5]

array([-0.79788824, -0.82153497, -0.73470684, -0.22282939, -0.23861815,
       -0.30522104, -0.65473938, -0.76172997, -0.37456588, -0.41971576,
       -0.70330844, -0.81646832, -0.81599387, -0.13852755, -0.13835434,
       -0.02931269, -0.47921602, -0.03351112,  0.        ,  0.        ,
       -0.31508094, -0.12149415,  0.        ,  0.        , -0.10241123,
       -0.72977012, -0.86782359, -0.43396639,  0.16663114, -0.58599503,
       -0.16816729, -0.28918085,  0.3546812 , -0.16338995, -0.65051147,
       -0.13602988, -0.25134893, -0.1981393 , -0.24483663, -0.23997933,
       -0.07735097, -0.89967715, -0.55930039,  0.39179484, -0.821208  ,
       -0.07969493, -0.00899006, -0.74930503,  2.12463865, -0.2456411 ,
        0.44496016, -0.82547384, -0.45684278,  0.37896411, -0.33784239,
       -0.32711135, -0.76504443, -0.04327968, -0.30885827, -0.32984964,
       -0.52117436, -0.56309851, -0.76610915, -0.7592844 ,  0.        ,
        0.        , -0.13469636, -0.11375119,  0.59721312, -0.90892764,
       -0.37443141,  0.        , -0.70964819, -0.41837235,  0.13840789,
       -0.35474453, -0.0971941 , -1.05396106, -0.34564292,  1.34010559,
        1.04304772, -0.77096695, -0.41721377, -0.76889204,  1.10007941,
       -0.46216929,  0.        , -0.3756006 ,  0.3756006 , -0.79031804,
        0.79031804,  0.40374336, -0.40374336,  0.        ,  0.        ])

## Ensemble Learners

In this section, you will compare two ensemble algorithms to determine which algorithm results in the best performance. You will train a Balanced Random Forest Classifier and an Easy Ensemble classifier . For each algorithm, be sure to complete the folliowing steps:

1. Train the model using the training data. 
2. Calculate the balanced accuracy score from sklearn.metrics.
3. Display the confusion matrix from sklearn.metrics.
4. Generate a classication report using the `imbalanced_classification_report` from imbalanced-learn.
5. For the Balanced Random Forest Classifier only, print the feature importance sorted in descending order (most important feature to least important) along with the feature score

Note: Use a random state of 1 for each algorithm to ensure consistency between tests

### Balanced Random Forest Classifier

In [13]:
# Resample the training data with the BalancedRandomForestClassifier
from imblearn.ensemble import BalancedRandomForestClassifier

brf = BalancedRandomForestClassifier(n_estimators=50, random_state=0)

brf.fit(Xtrained_data_scaled, y_train)

y_pred_brf = brf.predict(Xtest_data_scaled)

In [14]:
# Calculated the balanced accuracy score
balanced_accuracy_score(y_test, y_pred_brf)

0.752704769424557

In [15]:
# Display the confusion matrix
confusion_matrix(y_test, y_pred_brf)

array([[   65,    36],
       [ 2363, 14741]])

In [16]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test, y_pred_brf))

                   pre       rec       spe        f1       geo       iba       sup

  high_risk       0.03      0.64      0.86      0.05      0.74      0.54       101
   low_risk       1.00      0.86      0.64      0.92      0.74      0.57     17104

avg / total       0.99      0.86      0.64      0.92      0.74      0.57     17205

In [17]:
print("Balanced Random Forest classifier performance:")
print(
    f"Balanced accuracy: {balanced_accuracy_score(y_test, y_pred_brf):.2f} - "
    f"Geometric mean {geometric_mean_score(y_test, y_pred_brf):.2f}"
)

Balanced Random Forest classifier performance:
Balanced accuracy: 0.75 - Geometric mean 0.74

In [18]:
# List the features sorted in descending order by feature importance
importances = brf.feature_importances_ 
indices = np.argsort(importances)[::-1]
for f in range(X.shape[1]):
    print(f"{X.columns.values[indices[f]]}: ({importances[indices[f]]})")

last_pymnt_amnt: (0.0713305783331723)
total_rec_int: (0.06431713892039158)
total_rec_prncp: (0.060169883543945944)
total_pymnt_inv: (0.05737869914278982)
total_pymnt: (0.050570293006793145)
int_rate: (0.02886034432540519)
max_bal_bc: (0.022781431449247703)
out_prncp_inv: (0.01858293439868272)
revol_bal: (0.01798481764381934)
out_prncp: (0.017912974438228365)
annual_inc: (0.01765046337684286)
installment: (0.01700349183607852)
issue_d_Jan-2019: (0.01696684581600003)
dti: (0.016830830158220133)
total_bc_limit: (0.01604549819140594)
total_acc: (0.015420368480235742)
mths_since_recent_bc: (0.01538319306992853)
tot_hi_cred_lim: (0.014621684094556848)
bc_util: (0.014177445811235341)
total_bal_il: (0.013616502402257607)
avg_cur_bal: (0.013448949223507851)
acc_open_past_24mths: (0.013413386677349325)
mths_since_recent_inq: (0.01331814039693467)
il_util: (0.013236870918252153)
mo_sin_old_rev_tl_op: (0.013179782591257882)
mo_sin_old_il_acct: (0.01260114100273626)
total_rec_late_fee: (0.011739611243646248)
mths_since_rcnt_il: (0.011564329341254563)
loan_amnt: (0.011477677017679284)
issue_d_Mar-2019: (0.011385572645824113)
total_rev_hi_lim: (0.011196437142420976)
mo_sin_rcnt_rev_tl_op: (0.01091512279735194)
all_util: (0.010841785655078899)
total_bal_ex_mort: (0.010670316225669673)
open_rv_24m: (0.01036264095790171)
bc_open_to_buy: (0.01032015394955677)
tot_cur_bal: (0.009918561108912632)
mo_sin_rcnt_tl: (0.00990872572410912)
pct_tl_nvr_dlq: (0.009568081853356853)
total_il_high_credit_limit: (0.009469401938752417)
num_rev_tl_bal_gt_0: (0.00911945990726968)
num_rev_accts: (0.009065314950798885)
inq_last_12m: (0.00900556151118444)
num_actv_rev_tl: (0.008899759380372874)
total_cu_tl: (0.00889317713276805)
num_sats: (0.008553411951008694)
open_il_24m: (0.00849854641363258)
open_acc: (0.008358356962687467)
num_il_tl: (0.007921140267288632)
num_bc_tl: (0.007849639275845654)
inq_fi: (0.007350720132808606)
num_actv_bc_tl: (0.006938012764967519)
num_tl_op_past_12m: (0.0062563372019989434)
percent_bc_gt_75: (0.0059200845396057975)
num_op_rev_tl: (0.0058791053694271685)
inq_last_6mths: (0.005860678304243641)
open_acc_6m: (0.005759573640652778)
open_rv_12m: (0.005677069521785831)
num_bc_sats: (0.0052377428119166815)
open_il_12m: (0.005212037965560309)
tot_coll_amt: (0.004929230807025708)
issue_d_Feb-2019: (0.004887604913012088)
next_pymnt_d_May-2019: (0.00473470675731741)
mort_acc: (0.004650451522258287)
open_act_il: (0.004159335555884756)
next_pymnt_d_Apr-2019: (0.0041087244110716145)
delinq_2yrs: (0.0039016902782928855)
num_accts_ever_120_pd: (0.003648267555571703)
verification_status_Not Verified: (0.002993151284817286)
verification_status_Source Verified: (0.0028435744424152535)
home_ownership_MORTGAGE: (0.0026597176837217617)
application_type_Joint App: (0.0023277588403511555)
verification_status_Verified: (0.0019051383105908259)
pub_rec_bankruptcies: (0.0015953825583869094)
home_ownership_RENT: (0.0014241965717610063)
pub_rec: (0.0013800204017847533)
home_ownership_OWN: (0.0012357129820661876)
application_type_Individual: (0.0010650374547030506)
initial_list_status_f: (0.0010647290113575078)
initial_list_status_w: (0.0009428159629444767)
num_tl_90g_dpd_24m: (0.0005846217091065486)
collections_12_mths_ex_med: (0.000265346958347407)
chargeoff_within_12_mths: (0.0001531279178338002)
home_ownership_ANY: (0.00014181925276242845)
num_tl_30dpd: (0.0)
pymnt_plan_n: (0.0)
recoveries: (0.0)
collection_recovery_fee: (0.0)
policy_code: (0.0)
acc_now_delinq: (0.0)
num_tl_120dpd_2m: (0.0)
tax_liens: (0.0)
delinq_amnt: (0.0)
hardship_flag_N: (0.0)
debt_settlement_flag_N: (0.0)

### Easy Ensemble Classifier

In [19]:
# Train the Classifier
from sklearn.ensemble import AdaBoostClassifier
from imblearn.ensemble import EasyEnsembleClassifier

base_estimator = AdaBoostClassifier(n_estimators=10)
eec = EasyEnsembleClassifier(n_estimators=10, base_estimator=base_estimator)
eec.fit(Xtrained_data_scaled, y_train)
y_pred_eec = eec.predict(Xtest_data_scaled)

In [20]:
# Calculated the balanced accuracy score
balanced_accuracy_score(y_test, y_pred_eec)

0.8336857686002463

In [21]:
# Display the confusion matrix
confusion_matrix(y_test, y_pred_eec)

array([[   80,    21],
       [ 2133, 14971]])

In [22]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test, y_pred_eec))

                   pre       rec       spe        f1       geo       iba       sup

  high_risk       0.04      0.79      0.88      0.07      0.83      0.69       101
   low_risk       1.00      0.88      0.79      0.93      0.83      0.70     17104

avg / total       0.99      0.87      0.79      0.93      0.83      0.70     17205

In [23]:
print("Easy ensemble classifier performance:")
print(
    f"Balanced accuracy: {balanced_accuracy_score(y_test, y_pred_eec):.2f} - "
    f"Geometric mean {geometric_mean_score(y_test, y_pred_eec):.2f}"
)

Easy ensemble classifier performance:
Balanced accuracy: 0.83 - Geometric mean 0.83

### Final Questions

1. Which model had the best balanced accuracy score?

    Easy Ensemble Classifier

2. Which model had the best recall score?

    Easy Ensemble Classifier

3. Which model had the best geometric mean score?

    Easy Ensemble Classifier

4. What are the top three features?

    total_rec_prncp, total_pymnt & total_pymnt_inv